### Generated by rprotoc. DO NOT EDIT!
### <proto file: public/roguelike.proto>
# package roguelike;
# 
# message GameMessage {
#   required string command = 1;
#   repeated CellMessage cells = 2;
#   repeated CreatureMessage creatures = 3;
#   optional int32 player_id = 4;
#   repeated int32 fov = 5;
# }
# 
# message CellMessage {
#   required int32 id = 1;
#   required sint32 x = 2;
#   required sint32 y = 3;
#   required string symbol = 4;
#   optional int32 creature_id = 5;
#   optional int32 item_worth = 6;
# }
# 
# message CreatureMessage {
#   required int32 id = 1;
#   required sint32 x = 2;
#   required sint32 y = 3;
#   required string symbol = 4;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Roguelike
  class GameMessage < ::Protobuf::Message
    defined_in __FILE__
    required :string, :command, 1
    repeated :CellMessage, :cells, 2
    repeated :CreatureMessage, :creatures, 3
    optional :int32, :player_id, 4
    repeated :int32, :fov, 5
  end
  class CellMessage < ::Protobuf::Message
    defined_in __FILE__
    required :int32, :id, 1
    required :sint32, :x, 2
    required :sint32, :y, 3
    required :string, :symbol, 4
    optional :int32, :creature_id, 5
    optional :int32, :item_worth, 6
  end
  class CreatureMessage < ::Protobuf::Message
    defined_in __FILE__
    required :int32, :id, 1
    required :sint32, :x, 2
    required :sint32, :y, 3
    required :string, :symbol, 4
  end
end